name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show forge version
        run: forge --version

      - name: Install dependencies (OZ + forge-std)
        run: |
          mkdir -p lib
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.0.2
          forge install OpenZeppelin/openzeppelin-contracts@v5.0.2
          forge install foundry-rs/forge-std
          ls -la lib

      - name: Build
        run: forge build -vv
