name: Verify on BaseScan

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network"
        type: choice
        options: [sepolia, mainnet]
        default: mainnet
      implementation:
        description: "Implementation address (0x...)"
        required: true
      proxy:
        description: "Proxy address (0x...) — optional; verifies ERC1967Proxy too"
        required: false

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: |
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.0.2
          forge install OpenZeppelin/openzeppelin-contracts@v5.0.2
          forge install foundry-rs/forge-std
          forge build -vv

      - name: Set CHAIN + RPC
        run: |
          if [ "${{ github.event.inputs.network }}" = "sepolia" ]; then
            echo "CHAIN_ID=84532" >> $GITHUB_ENV
            echo "RPC_URL=${{ secrets.BASE_SEPOLIA_RPC_URL }}" >> $GITHUB_ENV
          else
            echo "CHAIN_ID=8453" >> $GITHUB_ENV
            echo "RPC_URL=${{ secrets.BASE_MAINNET_RPC_URL }}" >> $GITHUB_ENV
          fi

      - name: Verify Implementation (SplitBaseUpgradeable)
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          forge verify-contract \
            --chain-id $CHAIN_ID \
            --compiler-version v0.8.24 \
            --watch \
            ${{ github.event.inputs.implementation }} \
            src/SplitBaseUpgradeable.sol:SplitBaseUpgradeable

      - name: Try verify Proxy (ERC1967Proxy) if provided
        if: ${{ github.event.inputs.proxy != '' }}
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          # Берём конструкторные аргументы из broadcast (если деплойили этим же репо)
          FILE="broadcast/DeployUUPS.s.sol/$CHAIN_ID/run-latest.json"
          if [ -f "$FILE" ]; then
            ARGS=$(jq -r '.transactions[] | select(.contractName=="ERC1967Proxy") | .constructorArguments' "$FILE" | tail -n 1)
          else
            # Если файла нет, всё равно попробуем без аргументов (часто BaseScan сам свяжет прокси)
            ARGS=""
          fi

          if [ -n "$ARGS" ] && [ "$ARGS" != "null" ]; then
            forge verify-contract \
              --chain-id $CHAIN_ID \
              --compiler-version v0.8.24 \
              --constructor-args $ARGS \
              --watch \
              ${{ github.event.inputs.proxy }} \
              lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol:ERC1967Proxy
          else
            forge verify-contract \
              --chain-id $CHAIN_ID \
              --compiler-version v0.8.24 \
              --watch \
              ${{ github.event.inputs.proxy }} \
              lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol:ERC1967Proxy || true
          fi

      - name: Summary
        run: |
          echo "### Verification submitted" >> $GITHUB_STEP_SUMMARY
          echo "- Network: ${{ github.event.inputs.network }}" >> $GITHUB_STEP_SUMMARY
          echo "- Implementation: \`${{ github.event.inputs.implementation }}\`" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.inputs.proxy }}" != "" ]; then
            echo "- Proxy: \`${{ github.event.inputs.proxy }}\`" >> $GITHUB_STEP_SUMMARY
          fi
